runtime: python39  # Required by App Engine even for static sites
instance_class: F1

handlers:
  # This tells App Engine to serve index.html for the root URL
  - url: /
    static_files: index.html
    upload: index.html

  # This serves any other static files you might add later
  - url: /(.*)
    static_files: \1
    upload: (.*)