runtime: python39  # We use a basic runtime to enable static handlers
env: standard

handlers:
  # This tells Google to serve index.html when someone visits the root URL
  - url: /
    static_files: index.html
    upload: index.html

  # This handles any other files (like CSS or Images) if you add them later
  - url: /(.*)
    static_files: \1
    upload: (.*)